-------------------------------------------------------------------------------
Test set: de.tum.in.test.integration.AstAssertionTest$ForLoopTestTests
-------------------------------------------------------------------------------
Tests run: 4, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.021 s <<< FAILURE! - in de.tum.in.test.integration.AstAssertionTest$ForLoopTestTests
de.tum.in.test.integration.AstAssertionTest$ForLoopTestTests.test_testHasAtNoForLoop_Success  Time elapsed: 0.002 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Expected test 'testHasAtNoForLoop_Success' to be successful. Failure:

java.lang.AssertionError: The file /Users/markuspaulsen/Documents/UniPHD/ChristianFemers/GIT/src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/no/ClassWithNoKindsOfConditionals.java could not be read.
	at de.tum.in.test.testutilities.CustomConditions.generateFailure(CustomConditions.java:178)
	at de.tum.in.test.testutilities.CustomConditions.lambda$testSuccessRespectingDirectFailure$11(CustomConditions.java:151)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at de.tum.in.test.testutilities.CustomConditions.lambda$testSuccessRespectingDirectFailure$12(CustomConditions.java:149)
	at org.assertj.core.api.Condition.matches(Condition.java:161)
	at java.base/java.util.Optional.filter(Optional.java:218)
	at org.junit.platform.testkit.engine.Event.lambda$byPayload$0(Event.java:122)
	at org.assertj.core.api.Condition.matches(Condition.java:161)
	at org.assertj.core.condition.AllOf.lambda$matches$0(AllOf.java:63)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
Caused by: java.lang.AssertionError: The file /Users/markuspaulsen/Documents/UniPHD/ChristianFemers/GIT/src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/no/ClassWithNoKindsOfConditionals.java could not be read.
	at de.tum.in.test.api.ast.model.JavaFile.convertFromFile(JavaFile.java:58)
	at de.tum.in.test.api.ast.model.UnwantedNode.getUnwantedNodesForFileAt(UnwantedNode.java:66)
	at de.tum.in.test.api.ast.model.UnwantedNode.getMessageForUnwantedNodesForFileAt(UnwantedNode.java:119)
	at de.tum.in.test.api.ast.asserting.UnwantedNodesAssert.hasNo(UnwantedNodesAssert.java:95)
	at de.tum.in.test.integration.testuser.AstAssertionUser$ForLoopTests.testHasAtNoForLoop_Success(AstAssertionUser.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at de.tum.in.test.api.internal.TimeoutUtils.rethrowThrowableSafe(TimeoutUtils.java:47)
	at de.tum.in.test.api.internal.TimeoutUtils.lambda$performTimeoutExecution$1(TimeoutUtils.java:42)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

de.tum.in.test.integration.AstAssertionTest$ForLoopTestTests.test_testHasBelowNoForLoop_Success  Time elapsed: 0.002 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Expected test 'testHasBelowNoForLoop_Success' to be successful. Failure:

java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /usr/sbin/authserver
	at de.tum.in.test.testutilities.CustomConditions.generateFailure(CustomConditions.java:178)
	at de.tum.in.test.testutilities.CustomConditions.lambda$testSuccessRespectingDirectFailure$11(CustomConditions.java:151)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at de.tum.in.test.testutilities.CustomConditions.lambda$testSuccessRespectingDirectFailure$12(CustomConditions.java:149)
	at org.assertj.core.api.Condition.matches(Condition.java:161)
	at java.base/java.util.Optional.filter(Optional.java:218)
	at org.junit.platform.testkit.engine.Event.lambda$byPayload$0(Event.java:122)
	at org.assertj.core.api.Condition.matches(Condition.java:161)
	at org.assertj.core.condition.AllOf.lambda$matches$0(AllOf.java:63)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /usr/sbin/authserver
	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)
	at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at de.tum.in.test.api.ast.tool.PathTool.findMavenOrGradlePath(PathTool.java:57)
	at de.tum.in.test.integration.testuser.AstAssertionUser$ForLoopTests.testHasBelowNoForLoop_Success(AstAssertionUser.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at de.tum.in.test.api.internal.TimeoutUtils.rethrowThrowableSafe(TimeoutUtils.java:47)
	at de.tum.in.test.api.internal.TimeoutUtils.lambda$performTimeoutExecution$1(TimeoutUtils.java:42)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.AccessDeniedException: /usr/sbin/authserver
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:301)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374)
	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83)
	... 23 more

de.tum.in.test.integration.AstAssertionTest$ForLoopTestTests.test_testHasBelowNoForLoop_Fail  Time elapsed: 0.004 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: 
  "Unwanted statement found:
   - In src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/yes/ClassWithAnyKindsOfLoops.java:
    - For-Statement was found:
     - Between line 6 (column 3) and line 8 (column 3)"
 but was: 
  "Unwanted statement found:
   - In src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/yes/ClassWithAnyKindsOfLoops.java:
  - For-Statement was found:
     - Between line 6 (column 3) and line 8 (column 3)"
	at jdk.internal.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at de.tum.in.test.testutilities.CustomConditions.lambda$createMessageCondition$5(CustomConditions.java:88)
	at de.tum.in.test.testutilities.CustomConditions.lambda$createMessageCondition$7(CustomConditions.java:98)
	at org.junit.platform.commons.util.FunctionUtils.lambda$where$0(FunctionUtils.java:49)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	Suppressed: org.opentest4j.AssertionFailedError: Test 'testHasBelowNoForLoop_Fail' failed in an unexpected way:

TestExecutionResult [status = FAILED, throwable = java.lang.AssertionError: Unwanted statement found:
 - In src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/yes/ClassWithAnyKindsOfLoops.java:
- For-Statement was found:
   - Between line 6 (column 3) and line 8 (column 3)]

Expectations:
[✗] all of:[
   [✓] instance of java.lang.AssertionError,
   [✓] message is correctly localized,
   [✗] message is 'Unwanted statement found:
 - In src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/yes/ClassWithAnyKindsOfLoops.java:
  - For-Statement was found:
   - Between line 6 (column 3) and line 8 (column 3)'
]
		at de.tum.in.test.testutilities.CustomConditions.generateFailure(CustomConditions.java:178)
		at de.tum.in.test.testutilities.CustomConditions.generateFailure(CustomConditions.java:173)
		at de.tum.in.test.testutilities.CustomConditions.lambda$testFailRespectingDirectFailure$8(CustomConditions.java:124)
		at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
		at de.tum.in.test.testutilities.CustomConditions.lambda$testFailRespectingDirectFailure$10(CustomConditions.java:114)
		at org.assertj.core.api.Condition.matches(Condition.java:161)
		at java.base/java.util.Optional.filter(Optional.java:218)
		at org.junit.platform.testkit.engine.Event.lambda$byPayload$0(Event.java:122)
		at org.assertj.core.api.Condition.matches(Condition.java:161)
		at org.assertj.core.condition.AllOf.lambda$matches$0(AllOf.java:63)
	Caused by: java.lang.AssertionError: Unwanted statement found:
 - In src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/yes/ClassWithAnyKindsOfLoops.java:
- For-Statement was found:
   - Between line 6 (column 3) and line 8 (column 3)
		at java.base/java.util.Optional.ifPresent(Optional.java:178)
		at de.tum.in.test.integration.testuser.AstAssertionUser$ForLoopTests.testHasBelowNoForLoop_Fail(AstAssertionUser.java:38)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at de.tum.in.test.api.internal.TimeoutUtils.rethrowThrowableSafe(TimeoutUtils.java:47)
		at de.tum.in.test.api.internal.TimeoutUtils.lambda$performTimeoutExecution$1(TimeoutUtils.java:42)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)

de.tum.in.test.integration.AstAssertionTest$ForLoopTestTests.test_testHasAtNoForLoop_Fail  Time elapsed: 0.002 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: 
  "Unwanted statement found:
   - In src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/yes/ClassWithAnyKindsOfLoops.java:
    - For-Statement was found:
     - Between line 6 (column 3) and line 8 (column 3)"
 but was: 
  "Unwanted statement found:
  - In src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/yes/ClassWithAnyKindsOfLoops.java:
  - For-Statement was found:
     - Between line 6 (column 3) and line 8 (column 3)"
	at jdk.internal.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at de.tum.in.test.testutilities.CustomConditions.lambda$createMessageCondition$5(CustomConditions.java:88)
	at de.tum.in.test.testutilities.CustomConditions.lambda$createMessageCondition$7(CustomConditions.java:98)
	at org.junit.platform.commons.util.FunctionUtils.lambda$where$0(FunctionUtils.java:49)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	Suppressed: org.opentest4j.AssertionFailedError: Test 'testHasAtNoForLoop_Fail' failed in an unexpected way:

TestExecutionResult [status = FAILED, throwable = java.lang.AssertionError: Unwanted statement found:
- In src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/yes/ClassWithAnyKindsOfLoops.java:
- For-Statement was found:
   - Between line 6 (column 3) and line 8 (column 3)]

Expectations:
[✗] all of:[
   [✓] instance of java.lang.AssertionError,
   [✓] message is correctly localized,
   [✗] message is 'Unwanted statement found:
 - In src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/yes/ClassWithAnyKindsOfLoops.java:
  - For-Statement was found:
   - Between line 6 (column 3) and line 8 (column 3)'
]
		at de.tum.in.test.testutilities.CustomConditions.generateFailure(CustomConditions.java:178)
		at de.tum.in.test.testutilities.CustomConditions.generateFailure(CustomConditions.java:173)
		at de.tum.in.test.testutilities.CustomConditions.lambda$testFailRespectingDirectFailure$8(CustomConditions.java:124)
		at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
		at de.tum.in.test.testutilities.CustomConditions.lambda$testFailRespectingDirectFailure$10(CustomConditions.java:114)
		at org.assertj.core.api.Condition.matches(Condition.java:161)
		at java.base/java.util.Optional.filter(Optional.java:218)
		at org.junit.platform.testkit.engine.Event.lambda$byPayload$0(Event.java:122)
		at org.assertj.core.api.Condition.matches(Condition.java:161)
		at org.assertj.core.condition.AllOf.lambda$matches$0(AllOf.java:63)
	Caused by: java.lang.AssertionError: Unwanted statement found:
- In src/test/java/de/tum/in/test/integration/testuser/subject/structural/astTestFiles/loops/yes/ClassWithAnyKindsOfLoops.java:
- For-Statement was found:
   - Between line 6 (column 3) and line 8 (column 3)
		at java.base/java.util.Optional.ifPresent(Optional.java:178)
		at de.tum.in.test.integration.testuser.AstAssertionUser$ForLoopTests.testHasAtNoForLoop_Fail(AstAssertionUser.java:52)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at de.tum.in.test.api.internal.TimeoutUtils.rethrowThrowableSafe(TimeoutUtils.java:47)
		at de.tum.in.test.api.internal.TimeoutUtils.lambda$performTimeoutExecution$1(TimeoutUtils.java:42)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)

